name: CI/CD Pipeline

on:
  push:
    branches:
      - Sy_Moussa_emargement  # Branche spécifique
  pull_request:
    branches:
      - Sy_Moussa_emargement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v4

    - name: Installer Java et Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'  # Utiliser Java 23 car ton projet utilise cette version

    - name: Vérifier la version de Java
      run: java -version

    - name: Construire le projet avec Maven
      run: mvn clean install

    - name: Vérifier les fichiers générés
      run: ls -la target/

    - name: Construction de l'image Docker
      run: docker build -t moussasy23/projet_exam:latest .

    - name: Connexion à DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "moussasy23" --password-stdin

    - name: Pousser l'image sur DockerHub
      run: docker push moussasy23/projet_exam:latest  # Indentation corrigée ici
