name: CI/CD Pipeline

on:
  push:
    branches:
      - Sy_Moussa_emargement  # Branche spécifique
  pull_request:
    branches:
      - Sy_Moussa_emargement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v4

    - name: Installer Java 23 et Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'  # Utilisation d'Oracle JDK pour Java 23
        java-version: '23'      # Version Java 23 spécifiée

    - name: Vérifier la version de Java
      run: java -version

    - name: Build Maven
      run: mvn clean install

    - name: Construction de l'image Docker
      run: docker build -t moussa_sy/projet_exam:latest .

    - name: Connexion à DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pousser l'image sur DockerHub
      run: docker push moussa_sy/projet_exam:latest
